[package]
name = "urldecode"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.39", features=["derive"]}
owo-colors="4.2.1"
thiserror = "1.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]


